Repository jupyterhub/chartpress, pull requests merged in 2021-06, with the labels that each got.

#127 Define pre-commit hook
  .pre-commit-hooks.yaml
  setup.py
Labels: new

#128 Rename master to main
  .github/workflows/test.yaml
  RELEASE.md
  tests/conftest.py
  tests/test_repo_interactions.py
Labels: maintenance

#129 Update changelog for 1.2.0 release
  CHANGELOG.md
  RELEASE.md
Labels: documentation
