Repository jupyterhub/chartpress, pull requests merged in 2021-07, with the labels that each got.

#133 fix: mute handled git error messages
  chartpress.py
Labels: bug

#134 fix: use of github workflow tokens - different from PATs
  chartpress.py
  tests/test_helpers.py
Labels: bug

#135 Add changelog for 1.2.1
  CHANGELOG.md
Labels: documentation

#137 remove unused _strip_build_suffix_from_identifier
  chartpress.py
  tests/test_helpers.py
Labels: maintenance

#138 Add changelog for 1.3.0
  CHANGELOG.md
Labels: documentation
