Repository jupyterhub/chartpress, pull requests merged in 2022-08, with the labels that each got.

#173 pre-commit: add pyupgrade and isort (replaces reorder-python-imports)
  .pre-commit-config.yaml
  chartpress.py
  tests/test_chartpress.py
  tests/test_helpers.py
  tests/test_repo_interactions.py
Labels: maintenance

#150 Add `useChartVersion` and change appended version suffix (now like `1.2.3-0.dev.git.3.h123`)
  README.md
  chartpress.py
  tests/test_chartpress.py
  tests/test_commands.py
  tests/test_helpers.py
  tests/test_repo_interactions.py
Labels: new, breaking

#178 don't reset commit count on each tag
  README.md
  chartpress.py
  tests/test_repo_interactions.py
Labels: maintenance, breaking

#181 upload test coverage to codecov
  .github/workflows/test.yaml
  dev-requirements.txt
Labels: maintenance
